Sauvegarde && rdt systr0 && corrections mineures

diff --git a/includes/config/roles/backup/templates/restore.j2 b/includes/config/roles/backup/templates/restore.j2
--- a/includes/config/roles/backup/templates/restore.j2
+++ b/includes/config/roles/backup/templates/restore.j2
@@ -1,151 +1,189 @@
 #!/bin/bash
 
-ERROR_FILE=./errors.log
-EXIT=0
-ARCHIVE=""
+  clear
+  source /home/{{user.name}}/seedbox-compose/includes/functions.sh
+  logo
 
-# Définition des variables de couleurs
-CSI="\033["
-CEND="${CSI}0m"
-CRED="${CSI}1;31m"
-CGREEN="${CSI}1;32m"
-CYELLOW="${CSI}1;33m"
-CCYAN="${CSI}0;36m"   
+  ERROR_FILE=/home/${USER}/errors.log
+  EXIT=0
+  ARCHIVE=""
+
+  # Définition des variables de couleurs
+  CSI="\033["
+  CEND="${CSI}0m"
+  CRED="${CSI}1;31m"
+  CGREEN="${CSI}1;32m"
+  CYELLOW="${CSI}1;33m"
+  CCYAN="${CSI}0;36m"
+  BLUE='\e[0;36m'
 
 backupList() {
-
-    local backups=(/home/${SUDO_USER}/backup/backup-*)
-    local i=0
-    local n=""
-
-    if [[ ! -d /home/${SUDO_USER}/backup ]]; then
-	echo ""
-        echo -e "\n${CRED}"$(gettext "ERREUR: Aucune sauvegarde locale existante.")"${CEND}\n" 1>&2
-        exit 1
-    fi
-
-    echo -e "\n $(gettext "Liste des archives disponibles :")
-
-    for backup in ${backups[*]}; do
-        let "i += 1"
-        BACKUPPATH[$i]=$(stat -c "%n" "$backup")
-        echo -e "${CGREEN}   $i. ${BACKUPPATH[$i]##*/}${CEND}"
+  backups="/home/{{user.name}}/backup"
+  i=0
+  n=""
+    
+  # Vérifier si le dossier de sauvegarde est vide
+  if [ -z "$(ls -A "$backups")" ]; then
+    echo -e "\n${CRED}$(gettext "ERREUR: Aucune sauvegarde locale existante.")${CEND}\n" 1>&2
+      exit 1
+  else
+    echo
+    echo -e "${CGREEN}"$(gettext "Sauvegardes disponibles")"${CEND}"    
+    # Parcourir les sauvegardes disponibles
+    for backup in "$backups"/*; do
+      let "i += 1"
+      BACKUPPATH[$i]=$(stat -c "%n" "$backup")
+      echo -e "${BLUE}     $i. ${BACKUPPATH[$i]##*/}${CEND}"
     done
+  fi
 
+  if [ "$i" -eq 0 ]; then
+    echo -e "\n${CRED}$(gettext "ERREUR: Aucune sauvegarde locale existante.")${CEND}\n" 1>&2
+    return 1
+  fi
+
+  echo >&2 -n -e "${CGREEN}"$(gettext "Numéro du dossier à ouvrir : ")"${CEND}"
+  read -r n
+  echo
+  # Vérifier si le numéro du dossier est valide
+  if [[ $n -lt 1 ]] || [[ $n -gt $i ]]; then
+    echo -e "\n${CRED}$(gettext "ERREUR: Numéro de dossier invalide !")${CEND}"
     echo ""
-    echo >&2 -n -e "\e[32m"$(gettext "Saisir le numéro de l’archive à restaurer")"\e[0m"
-    read n
+    return 1
+  fi
 
+  # Récupérer le chemin du dossier sélectionné
+  selected_folder="${BACKUPPATH[$n]}"
+  echo -e "${CGREEN}"$(gettext "Liste des archives")"${CEND}"
+  counter=1
+  for file in "$selected_folder"/*; do
+    echo -e "${BLUE}     $counter. $(basename "$file")${CEND}"
+    ((counter++))
+  done
+  echo >&2 -n -e "${CGREEN}"$(gettext "Numéro de l'archive à restaurer : ")"${CEND}"
+  read -r selected_archive_number
 
-    if [[ $n -lt 1 ]] || [[ $n -gt $i ]]; then
-        echo -e "\n${CRED}"$(gettext "ERREUR: Numéro d'archive invalide !")"${CEND}"
-        echo ""
-        exit 1
-    fi
+  # Vérifier si le numéro de l'archive est valide
+  if [[ $selected_archive_number -lt 1 ]] || [[ $selected_archive_number -gt $counter ]]; then
+    echo -e "\n${CRED}$(gettext "ERREUR: Numéro d'archive invalide !")${CEND}"
+    echo ""
+    return 1
+  fi
 
-    ARCHIVEPATH=${BACKUPPATH[$n]##*/} # backup-JJMMAAAA-HHMM
-    ARCHIVE="$ARCHIVEPATH.tar.gz"
+  # Récupérer le nom de l'archive sélectionnée sans le chemin
+  ARCHIVE=$(basename "$(ls -1 "$selected_folder" | sed -n "${selected_archive_number}p")")
+  APPLI=$(basename "$(ls -1 "$selected_folder" | sed -n "${selected_archive_number}p")" | cut -d '-' -f1)
 }
 
 remoteRestoration() {
+  echo ""
+  echo -e "${CGREEN}"$(gettext "Sauvegardes disponibles")"${CEND}"    
+  rclone lsf crypt:/BACKUPS/ | sed 's:/.*::' | cat -n | sed 's/\([1-9].*\)/\1/' | awk '{print "\033[0;36m" $0 "\033[0m"}'
 
-path=/tmp/seedbox.txt
-backups=$(rclone --config /home/${SUDO_USER}/.config/rclone/rclone.conf lsf {{rclone.remote}}:/{{user.name}}/BACKUPS| sed 's:/.*::' | cat -n | sed 's/\([1-9].*\)/\1/')
+  # Demander à l'utilisateur de choisir un dossier
+  echo >&2 -n -e "${CGREEN}"$(gettext "Numéro du dossier à ouvrir : ")"${CEND}"
+  read -r folder_number
+  echo
+  # Vérifier si le numéro du dossier est valide
+  if [[ $folder_number -lt 1 ]] || [[ $folder_number -gt $(rclone lsf crypt:/BACKUPS/ | wc -l) ]]; then
+    echo -e "\n${CRED}$(gettext "ERREUR: Numéro de dossier invalide !")${CEND}"
+    echo ""
+    exit 1
+  fi
 
-echo -e "\n${CCYAN}Liste des archives disponibles :${CEND}"
-echo -e "${CGREEN}$backups${CEND}"
+  # Récupérer le nom du dossier sélectionné
+  selected_folder=$(rclone lsf crypt:/BACKUPS/ | sed 's:/.*::' | sed "${folder_number}q;d")
 
-rclone --config /home/${SUDO_USER}/.config/rclone/rclone.conf lsf {{rclone.remote}}:/{{user.name}}/BACKUPS | sed 's:/.*::' > $path
+  # Afficher le contenu du dossier sélectionné
+  echo -e "${CGREEN}"$(gettext "Liste des archives disponibles")"${CEND}"
+  rclone lsf crypt:/BACKUPS/"$selected_folder" | cat -n | awk '{print "\033[0;36m" $0 "\033[0m"}'
+  # Demander à l'utilisateur de choisir une archive
+  echo >&2 -n -e "${CGREEN}"$(gettext "Numéro de l'archive à restaurer : ")"${CEND}"
+  read -r archive_number
 
-echo ""
+  # Vérifier si le numéro de l'archive est valide
+  if [[ $archive_number -lt 1 ]] || [[ $archive_number -gt $(rclone lsf crypt:/BACKUPS/"$selected_folder" | wc -l) ]]; then
+    echo -e "\n${CRED}$(gettext "ERREUR: Numéro d'archive invalide !")${CEND}"
+    echo ""
+    exit 1
+  fi
 
-echo >&2 -n -e "\e[32m"$(gettext "Saisir le numéro de l’archive à restaurer")"\e[0m"
-read ligne
-
-
-BACKUPFOLDER=$(sed -n "$ligne"p $path)
-ARCHIVE="$BACKUPFOLDER.tar.gz"
-
-rm $path
+  # Récupérer le nom de l'archive sélectionnée
+  ARCHIVE=$(rclone lsf crypt:/BACKUPS/"$selected_folder" | sed "${archive_number}q;d")
+  APPLI=$(rclone lsf crypt:/BACKUPS/"$selected_folder" | sed "${archive_number}q;d" | cut -d '-' -f1)
 }
 
 localRestoration() {
 
-    echo ""
-    echo -e "${CRED}-------------------------------------------------------${CEND}"
-    echo -e "${CRED}ATTENTION :" $(gettext "RESTAURATION DU SERVEUR IMMINENTE")"${CEND}"
-    echo -e "${CRED}-------------------------------------------------------${CEND}"
+  echo ""
+  echo -e "${CRED}-------------------------------------------------------${CEND}"
+  echo -e "${CCYAN}ATTENTION :" $(gettext "Restauration imminente de $APPLI")"${CEND}"
+  echo -e "${CRED}-------------------------------------------------------${CEND}"
 
-    echo -e "\n"$(gettext "Appuyer sur") "${CCYAN}["$(gettext "ENTREE")"]${CEND}" $(gettext "pour démarrer la restauration ou CTRL+C pour quitter...")
-    read -r
-
-    echo $(gettext "> Récupération de l'archive locale")
-    cp /home/${SUDO_USER}/backup/"$ARCHIVEPATH"/*.tar.gz* .
-
+  echo -e "\n"$(gettext "Appuyer sur") "${CCYAN}["$(gettext "ENTREE")"]${CEND}" $(gettext "pour démarrer la restauration ou CTRL+C pour quitter...")
+  read -r
+  echo -e "${BLUE}"$(gettext "> Récupération de l'archive locale")"${CEND}"
+  sudo cp /home/{{user.name}}/backup/$APPLI/$ARCHIVE /
 }
 
 GdriveRestoration() {
+  echo ""
+  echo -e "${CRED}-------------------------------------------------------${CEND}"
+  echo -e "${CCYAN}ATTENTION :" $(gettext "Restauration imminente de $APPLI")"${CEND}"
+  echo -e "${CRED}-------------------------------------------------------${CEND}"
 
-    echo ""
-    echo -e "${CRED}-------------------------------------------------------${CEND}"
-    echo -e "${CRED}ATTENTION :" $(gettext "RESTAURATION DU SERVEUR IMMINENTE")"${CEND}"
-    echo -e "${CRED}-------------------------------------------------------${CEND}"
-
-    echo -e "\n"$(gettext "Appuyer sur") "${CCYAN}["$(gettext "ENTREE")"]${CEND}" $(gettext "pour démarrer la restauration ou CTRL+C pour quitter...")
-    read -r
-
-    echo $(gettext "> Récupération de l'archive distante")
-    rclone --config /home/${SUDO_USER}/.config/rclone/rclone.conf  copy {{rclone.remote}}:/{{user.name}}/BACKUPS/$BACKUPFOLDER/$ARCHIVE . --progress
+  echo -e "\n"$(gettext "Appuyer sur") "${CCYAN}["$(gettext "ENTREE")"]${CEND}" $(gettext "pour démarrer la restauration ou CTRL+C pour quitter...")
+  read -r
+  echo -e "${BLUE}"$(gettext "> Récupération de l'archive distante")"${CEND}"
+  sudo rclone --config "/home/{{user.name}}/.config/rclone/rclone.conf" copy crypt:BACKUPS/$APPLI/$ARCHIVE / --progress
 }
 
 fin() {
 
-    echo ""
-    echo -e "${CRED}-------------------------------------------------------${CEND}"
-    echo -e "${CRED}"$(gettext "RESTAURATION DU SERVEUR TERMINEE")"${CEND}"
-    echo -e "${CRED}-------------------------------------------------------${CEND}"
+  echo ""
+  echo -e "${CRED}-------------------------------------------------------${CEND}"
+  echo -e "${CCYAN}"$(gettext "Restauration terminée de $APPLI")"${CEND}"
+  echo -e "${CRED}-------------------------------------------------------${CEND}"
 
-    echo -e "\n $(gettext "Appuyer sur") ${CCYAN}[$(gettext "ENTREE")]${CEND} $(gettext "pour continuer")"
-    read -r
+  echo -e "\n $(gettext "Appuyer sur") ${CCYAN}[$(gettext "ENTREE")]${CEND} $(gettext "pour continuer")"
+  read -r
 }
 
-if [[ $EUID -ne 0 ]]; then
-    echo ""
-    echo -e "${CRED}"$(gettext "ERREUR: Vous devez être connecté en tant que root pour pouvoir exécuter ce script.")${CEND}" 1>&2
-    echo ""
-    exit 1
-fi
+  echo -e "${CRED}---------------------------------------${CEND}"
+  echo -e "${CCYAN}"$(gettext "Lancement de la restauration")"${CEND}"
+  echo -e "${CRED}---------------------------------------${CEND}"
+  echo ""
+  echo -e ${CGREEN}"$(gettext "Choisir le type de restauration")"${CEND}
+  echo -e  "${BLUE}     "1. Gdrive/Dropbox"${CEND}"
+  echo -e  "${BLUE}     "2. Locale"${CEND}"
+  echo -e "${CGREEN}---------------------------------------${CEND}"
+  echo -e "${CGREEN}     "$(gettext "3) Retour au menu principal")"${CEND}"
+  echo -e "${CGREEN}     "$(gettext "4) Retour au menu précédent")"${CEND}"
+  echo -e "${CGREEN}---------------------------------------${CEND}"
 
-clear
-
-echo ""
-echo -e "${CCYAN}#########################################################${CEND}"
-echo ""
-echo -e "${CCYAN}"$(gettext "DEMARRAGE DU SCRIPT DE RESTAURATION")"${CEND}"
-echo ""
-echo -e "${CCYAN}#########################################################${CEND}"
-echo ""
-
-echo $(gettext "Choisir le type de restauration :")
-echo "  1. Gdrive"
-echo "  2. Locale"
-echo ""
-
-while [[ $EXIT -eq 0 ]]; do
-
-    read -rp "Votre choix (1-2) : " RTYPE
-
+  while [[ $EXIT -eq 0 ]]; do
+    read -rp "Votre choix : " RTYPE
     case "$RTYPE" in
     "1")
-        echo -e $(gettext "Type de restauration sélectionnée :") "${CGREEN}Gdrive${CEND}"
+        clear
+        logo
+        echo -e "${CGREEN}"$(gettext "Type de restauration sélectionnée :")"${CEND}" "${BLUE}Gdrive/Dropbox${CEND}"
         remoteRestoration
 	GdriveRestoration
         EXIT=1
         ;;
     "2")
-        echo -e $(gettext "Type de restauration sélectionnée :") "${CGREEN}Locale${CEND}"
+        clear
+        logo
+        echo -e "${CGREEN}"$(gettext "Type de restauration sélectionnée :")"${CEND}" "${BLUE}Locale${CEND}"
         backupList
         localRestoration
+        EXIT=1
+        ;;
+    "3")
+        affiche_menu_db
+        ;;
+    "4")
         EXIT=1
         ;;
     *)
@@ -153,18 +191,16 @@ while [[ $EXIT -eq 0 ]]; do
         ;;
     esac
 
-done
+  done
+  cd /
+  echo ""
+  echo -e "${BLUE}"$(gettext "> Décompression de l'archive à la racine du système")"${CEND}"
+  tar xvf "$ARCHIVE" --absolute-names -C / 2> $ERROR_FILE
 
-echo "> Décompression de l'archive à la racine du système"
-sleep 3
-tar xvf "$ARCHIVE" --absolute-names -C / 2> $ERROR_FILE
-
-if [[ -s $ERROR_FILE ]]; then
+  if [[ -s $ERROR_FILE ]]; then
     echo -e "\n${CRED}"$(gettext "ERREUR: Echec de la décompression de l'archive.")"${CEND}"
     echo -e ""
     exit 1
-fi
-chown -R ${SUDO_USER} {{ settings.storage }}
-cd /root
-rm -rf "$ARCHIVE"
-fin
+  fi
+  sudo rm -rf "$ARCHIVE"
+  fin
